apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageserver
  labels:
    name: imageserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageserver
      name: imageserver
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: imageserver
        app: imageserver
    spec:
      containers:
      - name: imageserver
        imagePullPolicy: Always
        image: producercloud.azurecr.io/pc/image-server

---

kind: Service
apiVersion: v1
metadata:
  name:  images-port
spec:
  selector:
    app:  image-server
  type:  ClusterIP
  ports:
  - name:  images-port
    port:  3000
